In [1]:
import numpy as np

Задание 1.3.1

In [2]:
# chess_array = np.full((8,8), np.arange(0,8) % 2)
chess_array = np.zeros(64).reshape(8,8)
for i in range(1,9):
    for j in range(1,9):
        if ( (i - 1 + j - 1) % 2 == 1 ):
            chess_array[i - 1,j - 1] = 1
# map(lambda x : x % 2, chess_array)
print(chess_array)

# chess_array = np.full(64, int(lambda x : x % 2)).reshape(8,8)
# print(chess_array)


[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


Задание 1.3.2.

In [3]:
matrix1 = np.full((5,5), np.arange(0,5))
print(matrix1)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


Задание 1.3.3

In [4]:
l = 1
r = 10

matrix2 = np.random.random((3,3,3))

matrix2 = matrix2 * (r - l) + l
print(matrix2)

[[[9.60678339 1.08458946 9.28456375]
  [6.64207526 5.09783621 9.37857913]
  [8.38620327 9.64286658 1.79298815]]

 [[8.10807498 9.97660883 1.85845522]
  [3.33341903 8.62263726 3.46980621]
  [5.62872939 7.91990064 7.77259348]]

 [[1.16794054 8.94945081 5.70497865]
  [4.45227943 6.1038048  6.385506  ]
  [2.65608539 4.18877195 3.38175706]]]


Задание 1.3.4

In [5]:
matrix3 = np.zeros(64).reshape(8,8)
array_ones = np.ones(8)

matrix3[0,0:8] = array_ones
matrix3[7,0:8] = array_ones

matrix3[0:8, 0] = array_ones
matrix3[0:8, 7] = np.transpose(array_ones)

print(matrix3)
# array_ones

[[1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1.]]


Задание 1.3.5

In [6]:
array = np.random.random(100)
array = np.sort(array)[::-1]
print(array)

[0.99110265 0.98536982 0.9793711  0.97865046 0.94448554 0.93072122
 0.9186154  0.90128093 0.89933987 0.87756161 0.87399873 0.86309461
 0.85369987 0.84437398 0.83215708 0.82500417 0.81568337 0.80288125
 0.78970743 0.75889811 0.75868658 0.74340389 0.73366789 0.72385023
 0.71254939 0.6907797  0.68307432 0.6808257  0.67253277 0.66950142
 0.66060504 0.65700531 0.6429323  0.64268287 0.62557474 0.61258066
 0.60567439 0.60523408 0.60430181 0.59803774 0.59552317 0.57885634
 0.57651167 0.5736994  0.56560244 0.56356615 0.52392441 0.52196422
 0.51679529 0.51062234 0.49015619 0.48912196 0.46134995 0.45428751
 0.44491247 0.44070325 0.43773912 0.43755828 0.43058487 0.42373535
 0.40418926 0.4026562  0.39687183 0.36848755 0.35824843 0.33594408
 0.32484822 0.316658   0.30034673 0.29681029 0.29134234 0.28693263
 0.2726648  0.26900859 0.25483079 0.24250011 0.23963411 0.23883727
 0.23596601 0.2204917  0.19894084 0.19643079 0.19361565 0.16841924
 0.16515444 0.14251631 0.14056881 0.1225454  0.11822997 0.1073

Задание 1.3.6

In [7]:
matrix4 = np.random.random((3,3,3))
print(matrix4)

print("shape is: ", np.shape(matrix4))
print("dimensions are: ", np.ndim(matrix4))
print("size is: ", np.size(matrix4))

[[[0.87191054 0.80541295 0.25682438]
  [0.30224589 0.9634276  0.57302469]
  [0.59758861 0.41040872 0.66215657]]

 [[0.67253854 0.33991324 0.17391091]
  [0.96812107 0.27776693 0.58102975]
  [0.7724435  0.34122496 0.57060233]]

 [[0.21962538 0.94883429 0.47297388]
  [0.54767964 0.40787567 0.50176346]
  [0.80534918 0.44697812 0.6600865 ]]]
shape is:  (3, 3, 3)
dimensions are:  3
size is:  27


In [8]:
import pandas as pd

Задание 2.3.1

In [9]:
# dimension is 5
from cmath import sqrt
from math import dist

point1 = pd.Series([1,2,3,4,5])
point2 = pd.Series([5,4,3,2,1])

def distance(x, y) -> float:
    distance = 0
    size = x.size
    squaredResult = 0

    for i in range(0, size):
        squaredResult += (y[i] - x[i]) * (y[i] - x[i])
    
    return sqrt(squaredResult)

print(distance(point1, point2))
print(dist(point1,point2))

(6.324555320336759+0j)
6.324555320336759


Задание 2.3.2

In [10]:
data = pd.read_csv('C:\\Users\\averu\\github-local\\cs\\python\\abolone.csv')
data.head()

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

Задание 2.3.3

In [11]:
data.head(5)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
0      M   0.455     0.365   0.095        0.5140          0.2245   
1      M   0.350     0.265   0.090        0.2255          0.0995   
2      F   0.530     0.420   0.135        0.6770          0.2565   
3      M   0.440     0.365   0.125        0.5160          0.2155   
4      I   0.330     0.255   0.080        0.2050          0.0895   

   Viscera weight  Shell weight  Rings  
0          0.1010         0.150     15  
1          0.0485         0.070      7  
2          0.1415         0.210      9  
3          0.1140         0.155     10  
4          0.0395         0.055      7

In [12]:
data.tail(2)

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
4175      F   0.625     0.485   0.150        1.0945          0.5310   
4176      M   0.710     0.555   0.195        1.9485          0.9455   

      Viscera weight  Shell weight  Rings  
4175          0.2610         0.296     10  
4176          0.3765         0.495     12

In [13]:
data.shape

(4177, 9)

In [14]:
data.describe()

Length     Diameter       Height  Whole weight  Shucked weight  \
count  4177.000000  4177.000000  4177.000000   4177.000000     4177.000000   
mean      0.523992     0.407881     0.139516      0.828742        0.359367   
std       0.120093     0.099240     0.041827      0.490389        0.221963   
min       0.075000     0.055000     0.000000      0.002000        0.001000   
25%       0.450000     0.350000     0.115000      0.441500        0.186000   
50%       0.545000     0.425000     0.140000      0.799500        0.336000   
75%       0.615000     0.480000     0.165000      1.153000        0.502000   
max       0.815000     0.650000     1.130000      2.825500        1.488000   

       Viscera weight  Shell weight        Rings  
count     4177.000000   4177.000000  4177.000000  
mean         0.180594      0.238831     9.933684  
std          0.109614      0.139203     3.224169  
min          0.000500      0.001500     1.000000  
25%          0.093500      0.130000     8.000000  
50%          0.171000      0.234000     9.000000  
75%          0.253000      0.329000    11.000000  
max          0.760000      1.005000    29.000000

In [15]:
data.iloc[286:290]

Gender  Length  Diameter  Height  Whole weight  Shucked weight  \
286      M   0.530     0.435   0.155        0.6990          0.2880   
287      F   0.495     0.400   0.155        0.6445          0.2420   
288      M   0.440     0.355   0.125        0.4775          0.1320   
289      F   0.535     0.435   0.160        0.8105          0.3155   

     Viscera weight  Shell weight  Rings  
286          0.1595         0.205     10  
287          0.1325         0.205     17  
288          0.0815         0.190      9  
289          0.1795         0.240     10

In [16]:
# {F : Height >= .155, Rings >= 9} 
data1 = data[data['Gender'] == 'F'].head(5)
# data2 = data1[int(data1['Rings']) >= 10]
# data2.head(2)

Задание 3.3.2

In [17]:
from sklearn import preprocessing 

In [37]:
frame = pd.read_csv('C:\\Users\\averu\\github-local\\cs\\python\\iris.csv')
# frame.head(5)

feature1 = frame['sepal_length_cm'].array.reshape(-1,1)

# feature1

# Создание шкалировщика
MinMax_scale = preprocessing.MinMaxScaler(feature_range=(0,1))

# Шкалирование признака
scaled_feature1 = MinMax_scale.fit_transform(feature1)

feature1


<PandasArray>
[
[5.1],
[4.9],
[4.7],
[4.6],
[5.0],
[5.4],
[4.6],
[5.0],
[4.4],
[4.9],
[5.4],
[4.8],
[4.8],
[4.3],
[5.8],
[5.7],
[5.4],
[5.1],
[5.7],
[5.1],
[5.4],
[5.1],
[4.6],
[5.1],
[4.8],
[5.0],
[5.0],
[5.2],
[5.2],
[4.7],
[4.8],
[5.4],
[5.2],
[5.5],
[4.9],
[5.0],
[5.5],
[4.9],
[4.4],
[5.1],
[5.0],
[4.5],
[4.4],
[5.0],
[5.1],
[4.8],
[5.1],
[4.6],
[5.3],
[5.0],
[7.0],
[6.4],
[6.9],
[5.5],
[6.5],
[5.7],
[6.3],
[4.9],
[6.6],
[5.2],
[5.0],
[5.9],
[6.0],
[6.1],
[5.6],
[6.7],
[5.6],
[5.8],
[6.2],
[5.6],
[5.9],
[6.1],
[6.3],
[6.1],
[6.4],
[6.6],
[6.8],
[6.7],
[6.0],
[5.7],
[5.5],
[5.5],
[5.8],
[6.0],
[5.4],
[6.0],
[6.7],
[6.3],
[5.6],
[5.5],
[5.5],
[6.1],
[5.8],
[5.0],
[5.6],
[5.7],
[5.7],
[6.2],
[5.1],
[5.7],
[6.3],
[5.8],
[7.1],
[6.3],
[6.5],
[7.6],
[4.9],
[7.3],
[6.7],
[7.2],
[6.5],
[6.4],
[6.8],
[5.7],
[5.8],
[6.4],
[6.5],
[7.7],
[7.7],
[6.0],
[6.9],
[5.6],
[7.7],
[6.3],
[6.7],
[7.2],
[6.2],
[6.1],
[6.4],
[7.2],
[7.4],
[7.9],
[6.4],
[6.3],
[6.1],
[7.7],
[6.3],
[6.4],
[6.0],
[6.9],
[6.7

In [38]:
print("Mean:", round(scaled_feature1.mean()))
print("STD:", scaled_feature1.std())

Mean: 0
STD: 0.2292503588292058


In [39]:
feature2 = frame['sepal_width_cm'].array.reshape(-1,1)

# Создание шкалировщик
scaler = preprocessing.StandardScaler()

# Шкалирование признака
scaled_feature2 = scaler.fit_transform(feature2)

feature2

<PandasArray>
[
[3.5],
[3.0],
[3.2],
[3.1],
[3.6],
[3.9],
[3.4],
[3.4],
[2.9],
[3.1],
[3.7],
[3.4],
[3.0],
[3.0],
[4.0],
[4.4],
[3.9],
[3.5],
[3.8],
[3.8],
[3.4],
[3.7],
[3.6],
[3.3],
[3.4],
[3.0],
[3.4],
[3.5],
[3.4],
[3.2],
[3.1],
[3.4],
[4.1],
[4.2],
[3.1],
[3.2],
[3.5],
[3.1],
[3.0],
[3.4],
[3.5],
[2.3],
[3.2],
[3.5],
[3.8],
[3.0],
[3.8],
[3.2],
[3.7],
[3.3],
[3.2],
[3.2],
[3.1],
[2.3],
[2.8],
[2.8],
[3.3],
[2.4],
[2.9],
[2.7],
[2.0],
[3.0],
[2.2],
[2.9],
[2.9],
[3.1],
[3.0],
[2.7],
[2.2],
[2.5],
[3.2],
[2.8],
[2.5],
[2.8],
[2.9],
[3.0],
[2.8],
[3.0],
[2.9],
[2.6],
[2.4],
[2.4],
[2.7],
[2.7],
[3.0],
[3.4],
[3.1],
[2.3],
[3.0],
[2.5],
[2.6],
[3.0],
[2.6],
[2.3],
[2.7],
[3.0],
[2.9],
[2.9],
[2.5],
[2.8],
[3.3],
[2.7],
[3.0],
[2.9],
[3.0],
[3.0],
[2.5],
[2.9],
[2.5],
[3.6],
[3.2],
[2.7],
[3.0],
[2.5],
[2.8],
[3.2],
[3.0],
[3.8],
[2.6],
[2.2],
[3.2],
[2.8],
[2.8],
[2.7],
[3.3],
[3.2],
[2.8],
[3.0],
[2.8],
[3.0],
[2.8],
[3.8],
[2.8],
[2.8],
[2.6],
[3.0],
[3.4],
[3.1],
[3.0],
[3.1],
[3.1

In [40]:
print("Mean:", round(scaled_feature2.mean()))
print("STD:", scaled_feature2.std())

Mean: 0
STD: 0.9999999999999999
